# fly.toml app configuration file generated for smartcity-ride on 2023-10-18T14:01:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartcity-ride"
primary_region = "gru"

[build]

[env]
  DRIVE_FILE = "https://docs.google.com/spreadsheets/d/1EdqxBjr8ayXVW1GDnbHlQh-6m-Ca9jwqflGdMCbcTzk/gviz/tq?tqx=out:csv&sheet=Indicadores%20MMCISB"
  DRIVE_FORM_FILE = "https://docs.google.com/spreadsheets/d/11UWYEAG8O_JqONGw8PAqR_oX0TWzpF3kemAdSuhNI00/gviz/tq?tqx=out:csv&sheet=Respostas%20ao%20formulário%201"
  FLY_TOKEN = "fo1_Dh3M3_WltQsQvoRAY6bw3kwDK_mmb1mDSdPRyaJEkQA"
  SUPABASE_KEY_PUB = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvY25hbHJ4dGViaW9jaHF5dHZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTMzMTAyNzAsImV4cCI6MjAwODg4NjI3MH0.B2g5iPiLwB1iNsjQxQC1pQdIIiCz0UBe6QDJ4JRwT0A"
  SUPABASE_URL = "https://iocnalrxtebiochqytvs.supabase.co"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
