# fly.toml app configuration file generated for smartcity-ride-late-bush-6525-misty-moon-8935 on 2023-12-12T16:23:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartcity-ride-late-bush-6525-misty-moon-8935"
primary_region = "gru"

[build]

[env]
  DRIVE_FILE = "https://docs.google.com/spreadsheets/d/1EdqxBjr8ayXVW1GDnbHlQh-6m-Ca9jwqflGdMCbcTzk/gviz/tq?tqx=out:csv&sheet=Indicadores%20MMCISB"
  DRIVE_FORM_FILE = "https://docs.google.com/spreadsheets/d/11UWYEAG8O_JqONGw8PAqR_oX0TWzpF3kemAdSuhNI00/gviz/tq?tqx=out:csv&sheet=capacidades_form1"
  DRIVE_FORM_FILE2 = "https://docs.google.com/spreadsheets/d/11UWYEAG8O_JqONGw8PAqR_oX0TWzpF3kemAdSuhNI00/gviz/tq?tqx=out:csv&sheet=capacidades_form2"
  FLY_TOKEN = "fo1_Dh3M3_WltQsQvoRAY6bw3kwDK_mmb1mDSdPRyaJEkQA"
  SUPABASE_URL = "https://iocnalrxtebiochqytvs.supabase.co"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
